{
 "title": "voyager default dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "heatmap_buckets", "query": "${VAR_HEATMAP_BUCKETS}" },
   { "name": "axisWidth", "query": "${VAR_AXISWIDTH}" }
  ]
 },
 "panels": [
  { "title": "js-libp2p", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "libp2p bytes sent by protocol",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(\n    rate(libp2p_data_transfer_bytes_total{protocol!~\"global sent\", protocol=~\".* sent\"}[$__interval]),\n    \"protocol\",\n    \"$1\",\n    \"protocol\",\n    \"(.*) sent\"\n)",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "libp2p bytes sent by protocol",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(\n    rate(libp2p_data_transfer_bytes_total{protocol!~\"global sent\", protocol=~\".* sent\"}[$__interval]),\n    \"protocol\",\n    \"$1\",\n    \"protocol\",\n    \"(.*) sent\"\n)",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "libp2p bytes received by protocol",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(\n    rate(libp2p_data_transfer_bytes_total{protocol!~\"global received\", protocol=~\".* received\"}[$__interval]),\n    \"protocol\",\n    \"$1\",\n    \"protocol\",\n    \"(.*) received\"\n)",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "libp2p bytes received by protocol",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "label_replace(\n    rate(libp2p_data_transfer_bytes_total{protocol!~\"global received\", protocol=~\".* received\"}[$__interval]),\n    \"protocol\",\n    \"$1\",\n    \"protocol\",\n    \"(.*) received\"\n)",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "libp2p_dial_queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "expr": "libp2p_dial_queue", "legendFormat": "{{libp2p_dial_queue}}" }
   ]
  },
  {
   "title": "libp2p_dial_queue",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    { "expr": "libp2p_dial_queue", "legendFormat": "{{libp2p_dial_queue}}" }
   ]
  },
  {
   "title": "libp2p_tcp_dialer_events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(libp2p_tcp_dialer_events_total[$__rate_interval])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "libp2p_tcp_dialer_events",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "rate(libp2p_tcp_dialer_events_total[$__interval])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "libp2p kad dht ping queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    { "expr": "libp2p_kad_dht_ping_queue", "legendFormat": "{{libp2p_kad_dht_ping_queue}}" }
   ]
  },
  {
   "title": "libp2p kad dht ping queue",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    { "expr": "libp2p_kad_dht_ping_queue", "legendFormat": "{{libp2p_kad_dht_ping_queue}}" }
   ]
  },
  {
   "title": "libp2p kad dht query seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "libp2p_kad_dht_query_time_seconds",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "libp2p kad dht query seconds sum over 5s",
   "type": "heatmap",
   "description": "libp2p_kad_dht_query_time_seconds is a gauge metric that we create buckets out of using prometheus recording rules",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "sum_over_time(libp2p_kad_dht_query_time_seconds[5s])",
     "legendFormat": "5s sum"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "NodeJS GC Count by type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "targets": [
      {
       "expr": "rate(nodejs_gc_duration_seconds_count[$__interval])",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "NodeJS GC time spent by type",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
     "targets": [
      {
       "expr": "rate(nodejs_gc_duration_seconds_sum[$__interval])",
       "legendFormat": "{{kind}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NodeJS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "nodejs_active_resources",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "targets": [
      { "expr": "nodejs_active_resources", "legendFormat": "{{type}}" }
     ]
    },
    {
     "title": "nodejs_active_resources",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "targets": [
      { "expr": "nodejs_active_resources", "legendFormat": "{{type}}" }
     ]
    },
    {
     "title": "nodejs_active_handles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "nodejs_active_handles{instance=\"voyager:9090\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "nodejs_active_handles",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "targets": [
      {
       "expr": "nodejs_active_handles{instance=\"prometheus:9090\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "nodejs_memory_usage_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "nodejs_memory_usage_bytes", "legendFormat": "{{memory}}" }
     ]
    },
    {
     "title": "nodejs_memory_usage_bytes",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "targets": [
      { "expr": "nodejs_memory_usage_bytes", "legendFormat": "{{memory}}" }
     ]
    }
   ]
  }
 ]
}